---
- name: Set up NFS mounts for containers
  hosts: proxmox_nodes
  roles:
    - nfs_mount

- name: Create containers
  hosts: containers
  gather_facts: no
  roles:
    - create_containers

- name: Install common tools and run common tasks
  hosts: containers
  roles:
    - common

- name: Install and configure nextcloud
  hosts: swablu
  roles:
    - nextcloud

- name: Install and configure postgres
  hosts: magneton
  roles:
    - postgres
