---
- name: Set up NFS mounts for containers
  hosts: proxmox_nodes
  roles:
    - nfs_mount

- name: Create containers
  hosts: containers
  gather_facts: no
  roles:
    - create_containers

- name: Create VMs
  hosts: virtual_machines
  gather_facts: no
  roles:
    - create_vms

- name: Install common tools and run common tasks
  hosts: containers
  roles:
    - common

- name: Install and configure nextcloud
  hosts: swablu
  roles:
    - nextcloud

- name: Install and configure postgres
  hosts: magneton
  roles:
    - postgres

- name: Set up smultronfeet.nu
  hosts: hitmonlee
  roles:
    - smultron_feet

- name: Install and configure nginx reverse-proxy
  hosts: shuckle
  roles:
    - nginx_proxy

- name: Install and configure certbot
  hosts: jirachi
  roles:
    - certbot

- name: Install and configure Jellyfin
  hosts: mantine
  roles:
    - jellyfin

- name: Install and configure backups
  hosts: ditto
  roles:
    - backup

# TODO: Set up a play that runs a specific role for each host, with the free strategy, allowing for parallelism

