---
- name: Install common tools and run common tasks
  hosts: all
  roles:
    - common

- name: Install and configure nginx
  hosts: webservers
  roles:
    - nginx

- name: Install and configure nextcloud
  hosts: swablu
  roles:
    - nextcloud
