---
- name: Install Duplicacy
  ansible.builtin.get_url:
    url: https://github.com/gilbertchen/duplicacy/releases/download/v2.7.2/duplicacy_linux_x64_2.7.2
    dest: /usr/local/bin/duplicacy
    mode: '755'

- name: Ensure Duplicacy folder is created
  ansible.builtin.file:
    path: /mnt/backup/duplicacy
    state: directory

- name: Ensure logs folder is created
  ansible.builtin.file:
    path: /mnt/backup/log
    state: directory

- name: Install Duplicacy scripts
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/root/{{item}}"
    mode: '755'
  loop:
    - 'backup.sh'
    - 'initialize.sh'
    - 'set_password_vars.py'

- name: Check if duplicacy has been initialized
  ansible.builtin.stat:
    path: /root/.duplicacy/preferences
  register: duplicacy_prefs

- name: Init Duplicacy repos
  when: not duplicacy_prefs.stat.exists
  ansible.builtin.shell:
    cmd: /root/initialize.sh

- name: Set backup filters
  ansible.builtin.copy:
    src: filters
    dest: /root/.duplicacy/filters

- name: Install h5b cronjob key
  ansible.posix.authorized_key:
    user: root
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINe/sP5mrb0e24rdlcidMHC8Kttr8SGJ2zc5jvNU5xid jlh@charmander"
    state: present
