---

- name: Create containers
  community.general.proxmox:
    proxmox_default_behavior: no_defaults
    api_host: "{{ pve_fqdn }}"
    api_user: "{{ pve_user }}"
    vmid: "{{ proxmox_vmid }}"
    node: 'pve'
    hostname: "{{ hostname }}"
    unprivileged: "{{ proxmox_unprivileged }}"
    pubkey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL3SgUXbiLoKcBll6u10EEQ6hThrowtDxIkusD9oJpJO jlh@charmander'

    ostemplate: "local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz"

    mounts: "{{ proxmox_mounts }}"

    disk: "8"
    storage: "local-zfs"

    memory: "{{ proxmox_memory }}"
    swap: 0

    # Use the template in ./templates/netif.j2 to format the netif string
    netif: "{{ lookup('template', './templates/netif.j2') }}"

    onboot: yes
    state: "present"
    description: "{{ proxmox_description }}"
  delegate_to: localhost
  register: container_present

- name: Start container and update host key
  block:
    - name: Run extra container setup
      shell: "{{ proxmox_script }}"
      delegate_to: shodan
      when: proxmox_script is defined
    - name: Purge SSH host key for container
      known_hosts:
        name: "{{ fqdn }}"
        state: absent
    - name: Flush Local systemd-resolved DNS cache
      ansible.builtin.shell: sleep 5 && resolvectl flush-caches
    - name: Start container
      community.general.proxmox:
        proxmox_default_behavior: no_defaults
        api_host: "{{ pve_fqdn }}"
        api_user: "{{ pve_user }}"
        vmid: "{{ proxmox_vmid }}"
        state: "started"
    - name: Wait for container to start
      wait_for:
        host: "{{ fqdn }}"
        port: 22
        search_regex: "OpenSSH"
        delay: 2
    - name: Add new host key
      shell: "ssh-keyscan {{ fqdn }} >> ~/.ssh/known_hosts"
  when: container_present.changed
  delegate_to: localhost

    # TODO: Run task on inventory, with task delegated to localhost