---

- name: restart nginx
  systemd:
    name: "nginx"
    state: restarted

- name: restart php-fpm
  systemd:
    name: "php{{ php_version }}-fpm"
    state: restarted

- name: restart redis-server
  systemd:
    name: redis
    state: restarted