- name: Install deps
  apt:
    name:
      - snapd
      - squashfuse
    state: present

- name: Do snapd install hack
  community.general.snap:
    name: certbot
    classic: yes
    state: present
  ignore_errors: yes
  # For whatever reason trying to install snaps in a container fails the first time, but works after that

- name: Install certbot
  community.general.snap:
    name: certbot
    classic: yes
    state: present

- name: Add certbot to PATH
  file:
    src: "/snap/bin/certbot"
    dest: "/usr/bin/certbot"
    state: link

- name: Enable certbot plugins
  command: snap set certbot trust-plugin-with-root=ok
  changed_when: False

- name: Install Cloudflare certbot plugin
  community.general.snap:
    name: certbot-dns-cloudflare
    classic: yes
    state: present

- name: Configure cloudflare plugin
  copy:
    content: "dns_cloudflare_api_token = {{ cloudflare_api_key }}"
    dest: /root/cloudflare.ini
    owner: root
    group: root
    mode: "600"

- name: Generate new certs
  command:
    cmd: "/snap/bin/certbot certonly -n --agree-tos -m mail@jlh.name \
--dns-cloudflare --dns-cloudflare-credentials /root/cloudflare.ini \
-d {{ item.domain }} {{ item.alts }}"
    creates: "/etc/letsencrypt/live/{{ item.domain }}/fullchain.pem"
  loop:
    - domain: 'jlh.name'
      alts: '-d *.jlh.name'
    - domain: 'smultronfeet.nu'
      alts: ''

# Certbot automatically adds its own systemd timer for renewal
