- name: Install deps
  apt:
    name:
      - snapd
      - squashfuse
    state: present

- name: Do snapd install hack
  community.general.snap:
    name: certbot
    classic: yes
    state: present
  ignore_errors: yes
  # For whatever reason trying to install snaps in a container fails the first time, but works after that

- name: Install certbot
  community.general.snap:
    name: certbot
    classic: yes
    state: present

#- name: Add certbot to PATH
#    file:
#      src: "{{ apache_server_root[ansible_os_family] }}/conf-available/letsencrypt.conf"
#      dest: "{{ apache_server_root[ansible_os_family] }}/conf-enabled/letsencrypt.conf"
#      state: link

# Webserver config
#- name: Install nginx.conf
#  template:
#    src: nginx.conf.j2
#    dest: /etc/nginx/nginx.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify: restart nginx
#
#- name: Install PHP configuration
#  copy:
#    src: "php/{{ item }}"
#    dest: "/etc/php/{{ php_version }}/{{ item }}"
#    owner: root
#    group: root
#    mode: 0644
#  loop:
#    - 'fpm/php.ini'
#    - 'cli/php.ini'
#  notify: restart php-fpm
#
#- name: Install php-fpm.ini
#  template:
#    src: php-fpm.conf.j2
#    dest: /etc/php/{{ php_version }}/fpm/php-fpm.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify: restart php-fpm
#
#- name: Install cli/php.ini
#  template:
#    src: poolwww.conf.j2
#    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify: restart php-fpm
