---

- name: Mount nextcloud share
  mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/water/nextcloud
    path: /mnt/pve/nextcloud
    state: mounted

- name: Mount database share
  mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/water/database
    path: /mnt/pve/database
    state: mounted

- name: Mount certificate share
  mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/water/acme-certs
    path: /mnt/pve/acme-certs
    state: mounted

- name: Mount media share
  mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/vampire/media
    path: /mnt/pve/media
    state: mounted

