---

- name: Mount nextcloud share
  ansible.posix.mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/solid/nextcloud
    path: /mnt/pve/nextcloud
    opts: noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
    state: mounted

- name: Mount database share
  ansible.posix.mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/solid/database
    path: /mnt/pve/database
    opts: noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
    state: mounted

- name: Mount certificate share
  ansible.posix.mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/solid/acme-certs
    path: /mnt/pve/acme-certs
    opts: noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
    state: mounted

- name: Mount solid shares for backup
  ansible.posix.mount:
    fstype: nfs
    src: "freenas.home.jlh.name:/mnt/solid/{{ item }}"
    path: "/mnt/pve/solid/{{ item }}"
    opts: ro,noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
    state: mounted
  loop:
    - nextcloud
    - acme-certs
    - database

- name: Mount backup share
  ansible.posix.mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/water
    path: /mnt/pve/water
    opts: noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
    state: mounted
