---

- name: Mount nextcloud share
  ansible.posix.mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/solid/nextcloud
    path: /mnt/pve/nextcloud
    opts: noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
    state: mounted

- name: Mount database share
  ansible.posix.mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/solid/database
    path: /mnt/pve/database
    opts: noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
    state: mounted

- name: Mount certificate share
  ansible.posix.mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/solid/acme-certs
    path: /mnt/pve/acme-certs
    opts: noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
    state: mounted

- name: Mount media share
  ansible.posix.mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/vampire/media
    path: /mnt/pve/media
    opts: noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
    state: mounted

- name: Mount solid disk share
  ansible.posix.mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/solid
    path: /mnt/pve/solid
    opts: ro,noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
    state: mounted

- name: Mount backup share
  ansible.posix.mount:
    fstype: nfs
    src: freenas.home.jlh.name:/mnt/vampire/backup
    path: /mnt/pve/backup
    opts: noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
    state: mounted
