---
- name: Update software
  apt:
    upgrade: safe
    autoremove: yes

- name: Install common tools
  apt:
    name:
      - htop
      - gpg
      - git
    state: present
  become: true

- name: Clean package cache
  apt:
    autoclean: yes
