hostname: "jirachi"
fqdn: "{{hostname}}.home.jlh.name"
proxmox_vmid: "204"
proxmox_unprivileged: yes
proxmox_mounts: '{"mp0":"/mnt/pve/acme-certs/,mp=/etc/letsencrypt"}'
proxmox_memory: 1024
proxmox_description: ACME Certificate granter
# Add extra bit to pve config to make snaps work inside container
proxmox_script: "echo \"features: fuse=1,mount=fuse,nesting=1\" >> /etc/pve/lxc/204.conf"

ansible_host: "{{fqdn}}"